Repository Altinity/ClickHouse, pull requests merged in 2025-10, with the labels that each got.

#1047 Antalya 25.6: Do not send crash reports
  programs/server/config.xml
Labels: port-everywhere, antalya-25.6, antalya-25.6.5

#1019 Read optimization using Iceberg metadata
  src/Core/Range.cpp
  src/Core/Range.h
  src/Core/Settings.cpp
  src/Core/SettingsChangesHistory.cpp
  src/Disks/ObjectStorages/IObjectStorage.cpp
  src/Disks/ObjectStorages/IObjectStorage.h
  src/Processors/Chunk.cpp
  src/Storages/ObjectStorage/DataLakes/DataLakeConfiguration.h
  src/Storages/ObjectStorage/DataLakes/DeltaLakeMetadata.cpp
  src/Storages/ObjectStorage/DataLakes/DeltaLakeMetadata.h
  src/Storages/ObjectStorage/DataLakes/DeltaLakeMetadataDeltaKernel.cpp
  src/Storages/ObjectStorage/DataLakes/DeltaLakeMetadataDeltaKernel.h
  src/Storages/ObjectStorage/DataLakes/HudiMetadata.cpp
  src/Storages/ObjectStorage/DataLakes/HudiMetadata.h
  src/Storages/ObjectStorage/DataLakes/IDataLakeMetadata.cpp
  src/Storages/ObjectStorage/DataLakes/IDataLakeMetadata.h
  src/Storages/ObjectStorage/DataLakes/Iceberg/IcebergMetadata.cpp
  src/Storages/ObjectStorage/DataLakes/Iceberg/IcebergMetadata.h
  src/Storages/ObjectStorage/StorageObjectStorageSource.cpp
  src/Storages/ObjectStorage/StorageObjectStorageSource.h
  src/Storages/ObjectStorage/StorageObjectStorageStableTaskDistributor.cpp
  tests/integration/test_storage_iceberg/test.py
Labels: antalya, antalya-25.6, antalya-25.6.5

#1053 Antalya 25.6.5 Backport of 87733: Fix handling of timestamp(tz) columns in Glue Catalog
  ci/workflows/pull_request.py
  src/Databases/DataLake/GlueCatalog.cpp
Labels: antalya, antalya-25.6, antalya-25.6.5

#1055 25.6 update s3 paths
  .github/actions/create_workflow_report/ci_run_report.html.jinja
  .github/actions/create_workflow_report/create_workflow_report.py
  .github/grype/transform_and_upload_results_s3.sh
  .github/workflows/backport_branches.yml
  .github/workflows/grype_scan.yml
  .github/workflows/master.yml
  .github/workflows/merge_queue.yml
  .github/workflows/nightly_fuzzers.yml
  .github/workflows/nightly_jepsen.yml
  .github/workflows/nightly_statistics.yml
  .github/workflows/pull_request.yml
  .github/workflows/release_branches.yml
  ci/praktika/yaml_additional_templates.py
Labels: cicd, port-everywhere

#1057 Antalya 25.6 bitnami/ -> bitnamilegacy/
  tests/integration/compose/docker_compose_ldap.yml
Labels: cicd, port-everywhere, antalya-25.6, antalya-25.6.5
