Repository Altinity/ClickHouse, pull requests merged in 2025-05, with the labels that each got.

#750 Fix addresses_with_failover in cluster requests
  src/Interpreters/Cluster.cpp
  src/Interpreters/Cluster.h
Labels: antalya-25.2.2

#749 Fix stateless tests in antalya branch
  tests/broken_tests.json
  tests/queries/0_stateless/01271_show_privileges.reference
  tests/queries/0_stateless/02985_dialects_with_distributed_tables.reference
  tests/queries/0_stateless/02985_dialects_with_distributed_tables.sql
  tests/queries/0_stateless/02995_settings_25_1_4.tsv
Labels: antalya-25.2.2

#757 Fix macros for autodiscovery clusters
  src/Interpreters/ClusterDiscovery.cpp
  src/Interpreters/ClusterDiscovery.h
  src/Interpreters/Context.cpp
  tests/integration/test_cluster_discovery/config/macros.xml
  tests/integration/test_cluster_discovery/test.py
Labels: antalya-25.2.2

#770 Prune table in icebergCluster functions
  src/Storages/IStorageCluster.cpp
  src/Storages/IStorageCluster.h
  src/Storages/ObjectStorage/StorageObjectStorageCluster.cpp
  src/Storages/ObjectStorage/StorageObjectStorageCluster.h
  src/Storages/StorageDistributed.cpp
  src/Storages/StorageFileCluster.cpp
  src/Storages/StorageFileCluster.h
  src/Storages/StorageReplicatedMergeTree.cpp
  src/Storages/StorageURLCluster.cpp
  src/Storages/StorageURLCluster.h
  tests/integration/test_storage_iceberg/test.py
Labels: antalya-25.2.2

#729 24.3 Backport of #77766 and #59138 - Stop merges without written blocks / Fix REPLACE PARTITION waiting for mutations/merges on unrelated partitions
  src/Common/ActionBlocker.h
  src/Common/tests/gtest_action_blocker.cpp
  src/Storages/MergeTree/DataPartsExchange.h
  src/Storages/MergeTree/MergeProgress.h
  src/Storages/MergeTree/MergeTask.cpp
  src/Storages/MergeTree/MergeTask.h
  src/Storages/MergeTree/MergeTreeDataMergerMutator.h
  src/Storages/MergeTree/MutateTask.cpp
  src/Storages/MergeTree/MutateTask.h
  src/Storages/MergeTree/PartitionActionBlocker.cpp
  src/Storages/MergeTree/PartitionActionBlocker.h
  src/Storages/MergeTree/tests/gtest_partition_action_blocker.cpp
  src/Storages/StorageMergeTree.cpp
  src/Storages/StorageMergeTree.h
  tests/queries/0_stateless/02861_alter_replace_partition_do_not_wait_mutations_on_unrelated_partitions.reference
  tests/queries/0_stateless/02861_alter_replace_partition_do_not_wait_mutations_on_unrelated_partitions.sh
Labels: 24.3.next-required

#791 Antalya update grype tag
  .github/grype/run_grype_scan.sh
  .github/workflows/grype_scan.yml
Labels: antalya-25.2.2, antalya, antalya-25.2, cicd

#798 25.3 Antalya port - Alternative syntax for cluster functions
  src/Analyzer/FunctionSecretArgumentsFinderTreeNode.h
  src/Core/Settings.cpp
  src/Core/SettingsChangesHistory.cpp
  src/Databases/DataLake/DatabaseDataLake.cpp
  src/Databases/DataLake/DatabaseDataLakeSettings.cpp
  src/Disks/DiskType.cpp
  src/Disks/DiskType.h
  src/Interpreters/Cluster.cpp
  src/Interpreters/Cluster.h
  src/Interpreters/InterpreterCreateQuery.cpp
  src/Parsers/FunctionSecretArgumentsFinder.h
  src/Parsers/FunctionSecretArgumentsFinderAST.h
  src/Server/TCPHandler.cpp
  src/Storages/IStorage.h
  src/Storages/IStorageCluster.cpp
  src/Storages/IStorageCluster.h
  src/Storages/ObjectStorage/Azure/Configuration.cpp
  src/Storages/ObjectStorage/Azure/Configuration.h
  src/Storages/ObjectStorage/DataLakes/DataLakeConfiguration.h
  src/Storages/ObjectStorage/DataLakes/HudiMetadata.cpp
  src/Storages/ObjectStorage/HDFS/Configuration.cpp
  src/Storages/ObjectStorage/HDFS/Configuration.h
  src/Storages/ObjectStorage/Local/Configuration.cpp
  src/Storages/ObjectStorage/ReadBufferIterator.cpp
  src/Storages/ObjectStorage/S3/Configuration.cpp
  src/Storages/ObjectStorage/S3/Configuration.h
  src/Storages/ObjectStorage/StorageObjectStorage.cpp
  src/Storages/ObjectStorage/StorageObjectStorage.h
  src/Storages/ObjectStorage/StorageObjectStorageCluster.cpp
  src/Storages/ObjectStorage/StorageObjectStorageCluster.h
  src/Storages/ObjectStorage/StorageObjectStorageSettings.cpp
  src/Storages/ObjectStorage/StorageObjectStorageSink.cpp
  src/Storages/ObjectStorage/StorageObjectStorageSource.cpp
  src/Storages/ObjectStorage/Utils.cpp
  src/Storages/ObjectStorage/Utils.h
  src/Storages/ObjectStorage/registerStorageObjectStorage.cpp
  src/Storages/ObjectStorageQueue/StorageObjectStorageQueue.cpp
  src/Storages/ObjectStorageQueue/StorageObjectStorageQueue.h
  src/Storages/ObjectStorageQueue/registerQueueStorage.cpp
  src/Storages/extractTableFunctionFromSelectQuery.cpp
  src/Storages/extractTableFunctionFromSelectQuery.h
  src/TableFunctions/ITableFunction.h
  src/TableFunctions/ITableFunctionCluster.h
  src/TableFunctions/TableFunctionObjectStorage.cpp
  src/TableFunctions/TableFunctionObjectStorage.h
  src/TableFunctions/TableFunctionObjectStorageCluster.cpp
  src/TableFunctions/TableFunctionObjectStorageCluster.h
  src/TableFunctions/TableFunctionObjectStorageClusterFallback.cpp
  src/TableFunctions/TableFunctionObjectStorageClusterFallback.h
  src/TableFunctions/registerTableFunctions.cpp
  src/TableFunctions/registerTableFunctions.h
  tests/integration/test_s3_cluster/test.py
  tests/integration/test_storage_iceberg/test.py
Labels: antalya, antalya-25.3, antalya-25.3.3

#795 25.3 Antalya port - Parquet metadata caching
  programs/server/Server.cpp
  src/Access/Common/AccessType.h
  src/Common/ProfileEvents.cpp
  src/Core/FormatFactorySettings.h
  src/Core/ServerSettings.cpp
  src/Core/SettingsChangesHistory.cpp
  src/Interpreters/InterpreterSystemQuery.cpp
  src/Parsers/ASTSystemQuery.cpp
  src/Parsers/ASTSystemQuery.h
  src/Processors/Formats/IInputFormat.h
  src/Processors/Formats/Impl/ParquetBlockInputFormat.cpp
  src/Processors/Formats/Impl/ParquetBlockInputFormat.h
  src/Processors/Formats/Impl/ParquetFileMetaDataCache.cpp
  src/Processors/Formats/Impl/ParquetFileMetaDataCache.h
  src/Processors/Formats/Impl/ParquetMetadataInputFormat.cpp
  src/Processors/Formats/Impl/ParquetMetadataInputFormat.h
  src/Storages/ObjectStorage/StorageObjectStorageSource.cpp
  tests/queries/0_stateless/03299_parquet_object_storage_metadata_cache.reference
  tests/queries/0_stateless/03299_parquet_object_storage_metadata_cache.sql
Labels: antalya, antalya-25.3, antalya-25.3.3

#796 25.3 Antalya port #583, #584, #703, #720 - fixes for distributed calls
  src/Interpreters/ClusterProxy/executeQuery.cpp
  src/Interpreters/Context.cpp
  src/Interpreters/InterpreterSelectQuery.cpp
  src/Planner/Planner.cpp
  src/Processors/QueryPlan/ObjectFilterStep.cpp
  src/Processors/QueryPlan/ObjectFilterStep.h
  src/Processors/QueryPlan/Optimizations/optimizePrimaryKeyConditionAndLimit.cpp
  src/Processors/QueryPlan/QueryPlanStepRegistry.cpp
  src/Processors/QueryPlan/ReadFromRemote.cpp
  src/Processors/QueryPlan/ReadFromRemote.h
  src/QueryPipeline/RemoteQueryExecutor.cpp
  src/QueryPipeline/RemoteQueryExecutor.h
  src/Storages/IStorageCluster.cpp
  src/Storages/IStorageCluster.h
  src/Storages/ObjectStorage/StorageObjectStorageCluster.cpp
  src/Storages/ObjectStorage/StorageObjectStorageCluster.h
  tests/integration/test_storage_iceberg/test.py
Labels: antalya, antalya-25.3, antalya-25.3.3

#787 24.8 fix regression db upload
  .github/workflows/regression.yml
Labels: cicd, 24.8

#792 24.8 Add Grype Scan
  .github/create_combined_ci_report.py
  .github/create_workflow_report.py
  .github/grype/parse_vulnerabilities_grype.py
  .github/grype/run_grype_scan.sh
  .github/grype/transform_and_upload_results_s3.sh
  .github/workflows/grype_scan.yml
  .github/workflows/release_branches.yml
Labels: cicd, 24.8

#799 Antalya Update regression hash
  .github/workflows/release_branches.yml
Labels: antalya, antalya-25.2
