Repository Altinity/ClickHouse, pull requests merged in 2025-06, with the labels that each got.

#803 25.3 Antalya port of #688 - Role-based S3 access
  contrib/aws-cmake/CMakeLists.txt
  contrib/sparse-checkout/update-aws.sh
  docs/en/sql-reference/table-functions/s3.md
  docs/ru/sql-reference/table-functions/s3.md
  src/Disks/ObjectStorages/S3/diskSettings.cpp
  src/IO/S3/Credentials.cpp
  src/IO/S3/Credentials.h
  src/IO/S3AuthSettings.cpp
  src/Storages/ObjectStorage/S3/Configuration.cpp
  src/Storages/ObjectStorage/S3/Configuration.h
Labels: antalya, antalya-25.3, antalya-25.3.3

#834 25.3 Antalya port of #761 - Iceberg + tests
  src/Storages/ObjectStorage/DataLakes/DataLakeConfiguration.h
  src/Storages/ObjectStorage/StorageObjectStorage.h
  src/Storages/ObjectStorage/StorageObjectStorageCluster.cpp
  src/Storages/ObjectStorage/StorageObjectStorageCluster.h
  tests/integration/compose/docker_compose_glue_catalog.yml
  tests/integration/compose/docker_compose_iceberg_rest_catalog.yml
  tests/integration/test_database_glue/test.py
  tests/integration/test_mask_sensitive_info/test.py
  tests/integration/test_parquet_drop_metadata_cache/test.py
  tests/integration/test_s3_cache_locality/configs/named_collections.xml
  tests/integration/test_s3_cache_locality/test.py
  tests/integration/test_s3_cluster/test.py
  tests/integration/test_storage_iceberg/configs/config.d/named_collections.xml
  tests/integration/test_storage_iceberg/test.py
Labels: antalya, antalya-25.3, antalya-25.3.3

#839 25.3 Antalya - Bugfix for Iceberg: Take ownership of Context for IcebergMetadata
  src/Storages/ObjectStorage/DataLakes/Iceberg/IcebergMetadata.cpp
  src/Storages/ObjectStorage/DataLakes/Iceberg/IcebergMetadata.h
Labels: antalya, antalya-25.3, antalya-25.3.3, bugfix

#835 25.3 Antalya port of #756 - object storage cluster function
  src/Core/Settings.cpp
  src/Core/SettingsChangesHistory.cpp
  src/IO/ReadBufferFromS3.cpp
  src/Storages/IStorageCluster.cpp
  src/Storages/IStorageCluster.h
  src/Storages/ObjectStorage/DataLakes/DataLakeConfiguration.h
  src/Storages/ObjectStorage/DataLakes/DeltaLakeMetadata.h
  src/Storages/ObjectStorage/DataLakes/DeltaLakeMetadataDeltaKernel.cpp
  src/Storages/ObjectStorage/DataLakes/DeltaLakeMetadataDeltaKernel.h
  src/Storages/ObjectStorage/DataLakes/HudiMetadata.cpp
  src/Storages/ObjectStorage/DataLakes/HudiMetadata.h
  src/Storages/ObjectStorage/DataLakes/IDataLakeMetadata.h
  src/Storages/ObjectStorage/DataLakes/Iceberg/IcebergMetadata.cpp
  src/Storages/ObjectStorage/DataLakes/Iceberg/IcebergMetadata.h
  src/Storages/ObjectStorage/StorageObjectStorage.cpp
  src/Storages/ObjectStorage/StorageObjectStorage.h
  src/Storages/ObjectStorage/StorageObjectStorageCluster.cpp
  src/Storages/extractTableFunctionFromSelectQuery.cpp
  src/Storages/extractTableFunctionFromSelectQuery.h
  src/TableFunctions/TableFunctionRemote.h
  tests/integration/test_cluster_discovery/test.py
Labels: antalya, antalya-25.3, antalya-25.3.3

#814 25.3 Antalya Update regression hash
  .github/workflows/release_branches.yml
Labels: antalya, cicd, antalya-25.3, antalya-25.3.3

#841 25.3 Antalya - Iceberg: backport of #78688 and #78475
  docs/en/engines/table-engines/integrations/iceberg.md
  docs/en/sql-reference/table-functions/iceberg.md
  src/Storages/ObjectStorage/DataLakes/Iceberg/IcebergMetadata.cpp
  src/Storages/ObjectStorage/DataLakes/Iceberg/IcebergMetadata.h
  src/Storages/ObjectStorage/StorageObjectStorageSettings.cpp
  tests/integration/test_storage_iceberg/test.py
  tests/queries/0_stateless/03401_several_iceberg_tables_in_one_dir.reference
  tests/queries/0_stateless/03401_several_iceberg_tables_in_one_dir.sql
  tests/queries/0_stateless/data_minio/merged_several_tables_test/data/00000-0-7e41b120-8dbb-4f03-a487-fab888fe1037-0-00001.parquet
  tests/queries/0_stateless/data_minio/merged_several_tables_test/data/00000-2-3f64c5e4-85a1-4846-bca2-ec61df4bd056-0-00001.parquet
  tests/queries/0_stateless/data_minio/merged_several_tables_test/data/00000-4-21e1734e-704f-43d0-aef8-0d4baf8caaa3-0-00001.parquet
  tests/queries/0_stateless/data_minio/merged_several_tables_test/data/00001-1-7e41b120-8dbb-4f03-a487-fab888fe1037-0-00001.parquet
  tests/queries/0_stateless/data_minio/merged_several_tables_test/data/00001-3-3f64c5e4-85a1-4846-bca2-ec61df4bd056-0-00001.parquet
  tests/queries/0_stateless/data_minio/merged_several_tables_test/data/00001-5-21e1734e-704f-43d0-aef8-0d4baf8caaa3-0-00001.parquet
  tests/queries/0_stateless/data_minio/merged_several_tables_test/metadata/00001-1e2722c2-33bc-4e24-a119-224f22616082.metadata.json
  tests/queries/0_stateless/data_minio/merged_several_tables_test/metadata/00001-2aad93a8-a893-4943-8504-f6021f83ecab.metadata.json
  tests/queries/0_stateless/data_minio/merged_several_tables_test/metadata/00001-aec4e034-3f73-48f7-87ad-51b7b42a8db7.metadata.json
  tests/queries/0_stateless/data_minio/merged_several_tables_test/metadata/00002-0d450afb-f0d1-4fe7-a6c1-a75a4deb78d0.metadata.json
  tests/queries/0_stateless/data_minio/merged_several_tables_test/metadata/00002-4a776c8c-bb70-4422-8309-313bd05bc984.metadata.json
  tests/queries/0_stateless/data_minio/merged_several_tables_test/metadata/00002-c7c8a160-5d43-4705-87a1-dfabc4677b9c.metadata.json
  tests/queries/0_stateless/data_minio/merged_several_tables_test/metadata/12684bd2-2274-4262-962a-40f06681d0ad-m0.avro
  tests/queries/0_stateless/data_minio/merged_several_tables_test/metadata/5f3bf1e1-6bf9-42de-b42c-932989d02512-m0.avro
  tests/queries/0_stateless/data_minio/merged_several_tables_test/metadata/966c9c10-0bdb-4885-9654-22a3d4513c19-m0.avro
  tests/queries/0_stateless/data_minio/merged_several_tables_test/metadata/snap-1893158857028005124-1-5f3bf1e1-6bf9-42de-b42c-932989d02512.avro
  tests/queries/0_stateless/data_minio/merged_several_tables_test/metadata/snap-5813107004148504843-1-12684bd2-2274-4262-962a-40f06681d0ad.avro
  tests/queries/0_stateless/data_minio/merged_several_tables_test/metadata/snap-7645007302261205410-1-966c9c10-0bdb-4885-9654-22a3d4513c19.avro
Labels: antalya, antalya-25.3, antalya-25.3.3

#838 24.3 Port of #80334 - Allow to use named collections in ODBC/JDBC
  docs/en/engines/table-engines/integrations/jdbc.md
  docs/en/engines/table-engines/integrations/odbc.md
  docs/en/sql-reference/table-functions/jdbc.md
  docs/en/sql-reference/table-functions/odbc.md
  src/Storages/StorageXDBC.cpp
  src/TableFunctions/ITableFunctionXDBC.cpp
  tests/integration/test_odbc_interaction/configs/users.xml
  tests/integration/test_odbc_interaction/test.py
Labels: 24.3, 24.3.18

#823 24.8 update report to new format
  .github/create_workflow_report.py
  .github/workflows/release_branches.yml
Labels: cicd, 24.3.18, 24.8

#805 25.3 Antalya port of #743 - Object storage list objects cache
  programs/server/Server.cpp
  src/Access/Common/AccessType.h
  src/Common/ProfileEvents.cpp
  src/Common/TTLCachePolicy.h
  src/Core/ServerSettings.cpp
  src/Core/Settings.cpp
  src/Core/SettingsChangesHistory.cpp
  src/Disks/ObjectStorages/AzureBlobStorage/AzureObjectStorage.h
  src/Disks/ObjectStorages/IObjectStorage.h
  src/Disks/ObjectStorages/S3/S3ObjectStorage.h
  src/Interpreters/InterpreterSystemQuery.cpp
  src/Parsers/ASTSystemQuery.cpp
  src/Parsers/ASTSystemQuery.h
  src/Storages/Cache/ObjectStorageListObjectsCache.cpp
  src/Storages/Cache/ObjectStorageListObjectsCache.h
  src/Storages/Cache/tests/gtest_object_storage_list_objects_cache.cpp
  src/Storages/ObjectStorage/StorageObjectStorageSource.cpp
  src/Storages/ObjectStorage/StorageObjectStorageSource.h
  tests/queries/0_stateless/01271_show_privileges.reference
  tests/queries/0_stateless/03377_object_storage_list_objects_cache.reference
  tests/queries/0_stateless/03377_object_storage_list_objects_cache.sql
Labels: antalya, antalya-25.3, antalya-25.3.3

#833 24.8.14 Backport of #80710 -- Add support for Date32, DateTime64 in TTL
  .github/workflows/release_branches.yml
  docs/en/engines/table-engines/mergetree-family/mergetree.md
  src/Processors/TTL/ITTLAlgorithm.cpp
  src/Processors/TTL/ITTLAlgorithm.h
  src/Processors/TTL/TTLAggregationAlgorithm.cpp
  src/Processors/TTL/TTLColumnAlgorithm.cpp
  src/Processors/TTL/TTLDeleteAlgorithm.cpp
  src/Processors/TTL/TTLUpdateInfoAlgorithm.cpp
  src/Storages/MergeTree/MergeTreeDataWriter.cpp
  src/Storages/TTLDescription.cpp
  tests/queries/0_stateless/03519_ttl_extended_data_types.reference
  tests/queries/0_stateless/03519_ttl_extended_data_types.sql
Labels: 24.8, 24.8.14

#845 24.8 Smarter pr number fetching for grype and report and update report action
  .github/actions/create_workflow_report/action.yml
  .github/actions/create_workflow_report/ci_run_report.html.jinja
  .github/actions/create_workflow_report/create_workflow_report.py
  .github/grype/run_grype_scan.sh
  .github/workflows/grype_scan.yml
  .github/workflows/release_branches.yml
  .github/workflows/reusable_test.yml
  tests/ci/version_helper.py
Labels: cicd, 24.8, 24.8.14

#843 24.8.14 Backport of #79369 -- Ignore parse error in system.distributed_ddl_queue
  src/Storages/System/StorageSystemDDLWorkerQueue.cpp
  tests/integration/test_system_ddl_worker_queue/configs/remote_servers.xml
  tests/integration/test_system_ddl_worker_queue/test.py
Labels: 24.8, 24.8.14

#861 Antalya smarter pr number fetching for grype and report
  .github/actions/create_workflow_report/action.yml
  .github/actions/create_workflow_report/create_workflow_report.py
  .github/workflows/grype_scan.yml
  .github/workflows/release_branches.yml
  tests/ci/version_helper.py
Labels: antalya, antalya-25.2, cicd

#870 Antalya 25.3 Fix branding
  docker/server/README.md
  docker/server/README.src/logo.svg
  docs/ru/images/logo.svg
  docs/zh/images/logo.svg
  packages/clickhouse-client.yaml
  packages/clickhouse-common-static-dbg.yaml
  packages/clickhouse-keeper-dbg.yaml
  packages/clickhouse-keeper.yaml
  packages/clickhouse-server.yaml
  programs/server/binary.html
  programs/server/dashboard.html
  programs/server/merges.html
  programs/server/play.html
  utils/tests-visualizer/index.html
Labels: cicd, PORT-EVERYWHERE
