Repository Altinity/ClickHouse, pull requests merged in 2025-09, with the labels that each got.

#899 24.8 Fix branding
  docker/server/README.md
  docker/server/README.src/github-repo
  docker/server/README.src/license.md
  docker/server/README.src/logo.svg
  docker/server/README.src/maintainer.md
  docker/test/README.md
  docs/ru/images/logo.svg
  docs/zh/images/logo.svg
  packages/clickhouse-client.yaml
  packages/clickhouse-common-static-dbg.yaml
  packages/clickhouse-common-static.yaml
  packages/clickhouse-keeper-dbg.yaml
  packages/clickhouse-keeper.yaml
  packages/clickhouse-server.yaml
  programs/server/binary.html
  programs/server/dashboard.html
  programs/server/play.html
  src/Common/SignalHandlers.cpp
  utils/tests-visualizer/index.html
Labels: 24.8, 24.8.14, port-everywhere

#983 Antalya 25.6 Fix grype scan
  .github/actions/create_workflow_report/action.yml
  .github/actions/create_workflow_report/create_workflow_report.py
  .github/workflows/backport_branches.yml
  .github/workflows/grype_scan.yml
  .github/workflows/master.yml
  .github/workflows/merge_queue.yml
  .github/workflows/nightly_fuzzers.yml
  .github/workflows/nightly_jepsen.yml
  .github/workflows/nightly_statistics.yml
  .github/workflows/pull_request.yml
  .github/workflows/release_branches.yml
  ci/praktika/yaml_additional_templates.py
Labels: cicd, antalya-25.6, antalya-25.6.5

#970 Antalya 25.6.5 Backport of #83298 Do not throw exception on connection with incorrect iceberg database
  src/Databases/DataLake/DatabaseDataLake.cpp
Labels: antalya, antalya-25.6, antalya-25.6.5

#1001 Antalya 25.6.5 - Backport of #85538 - Few fixes to hive reads & writes
  src/Functions/keyvaluepair/impl/CHKeyValuePairExtractor.h
  src/Functions/keyvaluepair/impl/StateHandlerImpl.h
  src/Storages/HivePartitioningUtils.cpp
  src/Storages/HivePartitioningUtils.h
  src/Storages/IPartitionStrategy.cpp
  src/Storages/ObjectStorage/StorageObjectStorage.cpp
  src/Storages/ObjectStorage/StorageObjectStorage.h
  src/Storages/ObjectStorage/StorageObjectStorageCluster.cpp
  src/Storages/ObjectStorage/StorageObjectStorageSource.cpp
  src/Storages/ObjectStorage/registerStorageObjectStorage.cpp
  src/Storages/StorageFile.cpp
  src/Storages/StorageFileCluster.cpp
  src/Storages/StorageURL.cpp
  src/Storages/StorageURLCluster.cpp
  src/Storages/prepareReadingFromFormat.cpp
  src/TableFunctions/TableFunctionFile.cpp
  src/TableFunctions/TableFunctionObjectStorage.cpp
  src/TableFunctions/TableFunctionURL.cpp
  src/TableFunctions/TableFunctionURLCluster.cpp
  tests/queries/0_stateless/01545_url_file_format_settings.sql
  tests/queries/0_stateless/03203_hive_style_partitioning.reference
  tests/queries/0_stateless/03363_hive_style_partition.reference
  tests/queries/0_stateless/03363_hive_style_partition.sql
Labels: antalya, antalya-25.6, antalya-25.6.5

#997 Antalya 25.6.5 Green MasterCI
  .github/actions/create_workflow_report/action.yml
  .github/actions/create_workflow_report/workflow_report_hook.sh
  .github/workflows/backport_branches.yml
  .github/workflows/master.yml
  .github/workflows/merge_queue.yml
  .github/workflows/nightly_fuzzers.yml
  .github/workflows/nightly_jepsen.yml
  .github/workflows/nightly_statistics.yml
  .github/workflows/pull_request.yml
  .github/workflows/release_branches.yml
  ci/defs/job_configs.py
  ci/jobs/clickbench.py
  ci/jobs/scripts/clickhouse_proc.py
  ci/praktika/runner.py
  ci/praktika/yaml_additional_templates.py
  ci/workflows/master.py
Labels: cicd, antalya-25.6, antalya-25.6.5

#953 25.6.5 Antalya port of #860: Support different warehouses behind Iceberg REST catalog
  src/Databases/DataLake/ICatalog.cpp
  src/IO/S3/Client.cpp
  src/IO/S3/Client.h
  src/IO/S3/URI.cpp
  src/IO/S3/URI.h
  src/Storages/ObjectStorage/DataLakes/Iceberg/IcebergMetadata.cpp
  src/Storages/ObjectStorage/DataLakes/Iceberg/ManifestFile.cpp
  src/Storages/ObjectStorage/DataLakes/Iceberg/ManifestFile.h
  src/Storages/ObjectStorage/DataLakes/Iceberg/Utils.cpp
  src/Storages/ObjectStorage/DataLakes/Iceberg/Utils.h
Labels: antalya, antalya-25.6, antalya-25.6.5

#1009 simple export part
  src/Access/Common/AccessType.h
  src/CMakeLists.txt
  src/Core/ServerSettings.cpp
  src/Core/Settings.cpp
  src/Core/SettingsChangesHistory.cpp
  src/Databases/DatabaseReplicated.cpp
  src/Disks/ObjectStorages/IObjectStorage.h
  src/Interpreters/Context.cpp
  src/Interpreters/Context.h
  src/Interpreters/DDLWorker.cpp
  src/Interpreters/InterpreterAlterQuery.cpp
  src/Interpreters/PartLog.cpp
  src/Interpreters/PartLog.h
  src/Interpreters/executeDDLQueryOnCluster.cpp
  src/Parsers/ASTAlterQuery.cpp
  src/Parsers/ASTAlterQuery.h
  src/Parsers/CommonParsers.h
  src/Parsers/ParserAlterQuery.cpp
  src/Storages/IPartitionStrategy.cpp
  src/Storages/IPartitionStrategy.h
  src/Storages/IStorage.h
  src/Storages/MergeTree/MergeTreeData.cpp
  src/Storages/MergeTree/MergeTreeData.h
  src/Storages/MergeTree/MergeTreeExportManifest.h
  src/Storages/MergeTree/MergeTreeExportStatus.h
  src/Storages/MergeTree/MergeTreePartition.cpp
  src/Storages/MergeTree/MergeTreePartition.h
  src/Storages/MergeTree/MergeTreeSequentialSource.cpp
  src/Storages/MergeTree/MergeTreeSequentialSource.h
  src/Storages/ObjectStorage/MergeTree/StorageObjectStorageImporterSink.cpp
  src/Storages/ObjectStorage/MergeTree/StorageObjectStorageImporterSink.h
  src/Storages/ObjectStorage/ObjectStorageFilePathGenerator.h
  src/Storages/ObjectStorage/StorageObjectStorage.cpp
  src/Storages/ObjectStorage/StorageObjectStorage.h
  src/Storages/ObjectStorage/StorageObjectStorageCluster.cpp
  src/Storages/ObjectStorage/StorageObjectStorageCluster.h
  src/Storages/ObjectStorage/StorageObjectStorageSink.cpp
  src/Storages/ObjectStorage/StorageObjectStorageSink.h
  src/Storages/PartitionCommands.cpp
  src/Storages/PartitionCommands.h
  src/Storages/PartitionedSink.cpp
  src/Storages/PartitionedSink.h
  src/Storages/StorageFile.cpp
  src/Storages/StorageMergeTree.cpp
  src/Storages/StorageMergeTree.h
  src/Storages/StorageReplicatedMergeTree.cpp
  src/Storages/StorageReplicatedMergeTree.h
  src/Storages/StorageURL.cpp
  src/Storages/System/StorageSystemExports.cpp
  src/Storages/System/StorageSystemExports.h
  src/Storages/System/attachSystemTables.cpp
  tests/queries/0_stateless/01271_show_privileges.reference
  tests/queries/0_stateless/03572_export_merge_tree_part_to_object_storage.reference
  tests/queries/0_stateless/03572_export_merge_tree_part_to_object_storage.sh
  tests/queries/0_stateless/03572_export_merge_tree_part_to_object_storage_simple.reference
  tests/queries/0_stateless/03572_export_merge_tree_part_to_object_storage_simple.sql
  tests/queries/0_stateless/03572_export_replicated_merge_tree_part_to_object_storage.reference
  tests/queries/0_stateless/03572_export_replicated_merge_tree_part_to_object_storage.sh
  tests/queries/0_stateless/03572_export_replicated_merge_tree_part_to_object_storage_simple.reference
  tests/queries/0_stateless/03572_export_replicated_merge_tree_part_to_object_storage_simple.sql
Labels: antalya, antalya-25.6, antalya-25.6.5

#1016 Antalya 25.6.5 Update regression hash
  .github/workflows/backport_branches.yml
  .github/workflows/master.yml
  .github/workflows/merge_queue.yml
  .github/workflows/nightly_fuzzers.yml
  .github/workflows/nightly_jepsen.yml
  .github/workflows/nightly_statistics.yml
  .github/workflows/pull_request.yml
  .github/workflows/release_branches.yml
  ci/praktika/yaml_additional_templates.py
Labels: cicd, antalya-25.6, antalya-25.6.5

#1028 Antalya 25.6.5 - Backport of #85134 - Allow key-value arguments in s3/s3cluster engine
  src/Parsers/FunctionSecretArgumentsFinder.h
  src/Storages/ObjectStorage/S3/Configuration.cpp
  tests/integration/test_mask_sensitive_info/test.py
  tests/integration/test_storage_s3/test.py
  tests/integration/test_storage_s3/test_invalid_env_credentials.py
Labels: antalya-25.6, antalya-25.6.5

#1037 Antalya 25.6.5 - Backport of #87515 and #87621 - Never not put hive columns in format_header / Do not read hive columns as LC by default
  src/Storages/HivePartitioningUtils.cpp
  src/Storages/prepareReadingFromFormat.cpp
  tests/queries/0_stateless/03203_hive_style_partitioning.reference
  tests/queries/0_stateless/03631_hive_columns_not_in_format_header.reference
  tests/queries/0_stateless/03631_hive_columns_not_in_format_header.sql
Labels: antalya-25.6, antalya-25.6.5
