Repository Altinity/ClickHouse, pull requests merged in 2025-07, with the labels that each got.

#866 Antalya 25.3: lock_object_storage_task_distribution_ms setting
  src/Core/Settings.cpp
  src/Core/SettingsChangesHistory.cpp
  src/Disks/ObjectStorages/IObjectStorage.cpp
  src/Disks/ObjectStorages/IObjectStorage.h
  src/Storages/ObjectStorage/StorageObjectStorageCluster.cpp
  src/Storages/ObjectStorage/StorageObjectStorageSource.cpp
  src/Storages/ObjectStorage/StorageObjectStorageStableTaskDistributor.cpp
  src/Storages/ObjectStorage/StorageObjectStorageStableTaskDistributor.h
  tests/integration/test_s3_cache_locality/test.py
Labels: antalya, antalya-25.3, antalya-25.3.3, swarms

#860 Antalya 25.3: Support different warehouses behind Iceberg REST catalog
  src/Databases/DataLake/ICatalog.cpp
  src/IO/S3/Client.cpp
  src/IO/S3/Client.h
  src/IO/S3/URI.cpp
  src/IO/S3/URI.h
  src/Storages/ObjectStorage/DataLakes/Iceberg/IcebergMetadata.cpp
  src/Storages/ObjectStorage/DataLakes/Iceberg/ManifestFile.cpp
  src/Storages/ObjectStorage/DataLakes/Iceberg/ManifestFile.h
  src/Storages/ObjectStorage/DataLakes/Iceberg/Utils.cpp
  src/Storages/ObjectStorage/DataLakes/Iceberg/Utils.h
Labels: antalya, antalya-25.3, antalya-25.3.3

#878 Antalya 25.3 : Backport of #79844 - ObjectStorageCluster table function return wrong count() after applyTrivialCount optimized
  tests/integration/test_storage_iceberg/test.py
Labels: antalya, antalya-25.3, antalya-25.3.3

#893 25.3.5 Backport of #79147: Remove guard pages from fibers and alternative stack for signals in threads
  programs/keeper/Keeper.cpp
  src/Client/BuzzHouse/Generator/FuzzConfig.cpp
  src/Client/ClientBase.cpp
  src/Client/Connection.cpp
  src/Common/AsyncTaskExecutor.cpp
  src/Common/AsyncTaskExecutor.h
  src/Common/FiberStack.cpp
  src/Common/FiberStack.h
  src/Common/ThreadStatus.cpp
  src/Common/memory.cpp
  src/Common/memory.h
  src/Coordination/FourLetterCommand.h
  src/Storages/Distributed/DistributedAsyncInsertBatch.cpp
Labels: 25.3, 25.3.5

#894 25.3.5 Backport of #79743: Fix wrong results for grouping sets with ColumnConst
  src/Interpreters/ActionsDAG.cpp
  src/Interpreters/ActionsDAG.h
  src/Planner/PlannerExpressionAnalysis.cpp
  tests/queries/0_stateless/00757_enum_defaults_const_analyzer.reference
  tests/queries/0_stateless/03447_grouping_sets_analyzer_const_columns.reference
  tests/queries/0_stateless/03447_grouping_sets_analyzer_const_columns.sql
Labels: 25.3, 25.3.5

#898 Send iceberg_metadata_file_path setting to swarm node
  src/Storages/ObjectStorage/DataLakes/DataLakeConfiguration.cpp
  src/Storages/ObjectStorage/DataLakes/DataLakeConfiguration.h
Labels: antalya, antalya-25.3, antalya-25.3.3

#906 25.6 disable unused hooks in PR and master workflows
  .github/compare_ci_fails.py
  .github/workflows/backport_branches.yml
  .github/workflows/master.yml
  .github/workflows/merge_queue.yml
  .github/workflows/nightly_fuzzers.yml
  .github/workflows/nightly_jepsen.yml
  .github/workflows/nightly_statistics.yml
  .github/workflows/pull_request.yml
  .github/workflows/release_branches.yml
  ci/praktika/_environment.py
  ci/praktika/yaml_additional_templates.py
  ci/workflows/master.py
  ci/workflows/pull_request.py
  tests/ci/pr_info.py
Labels: antalya, antalya-25.6

#914 25.3.6 Backport of #79369 -- Ignore parse error in system.distributed_ddl_queue
  src/Storages/System/StorageSystemDDLWorkerQueue.cpp
Labels: 25.3, 25.3.6

#912 Iceberg as alias for DataLakeCatalog with catalog_type='rest'
  src/Databases/DataLake/DataLakeConstants.h
  src/Databases/DataLake/DatabaseDataLake.cpp
  src/Parsers/ASTSetQuery.cpp
  tests/integration/test_database_iceberg/test.py
Labels: 25.3, 25.3.6

#915 25.3.6 Backport of #79743: Fix wrong results for grouping sets with ColumnConst
  src/Interpreters/ActionsDAG.cpp
  src/Interpreters/ActionsDAG.h
  src/Planner/PlannerExpressionAnalysis.cpp
  tests/queries/0_stateless/00757_enum_defaults_const_analyzer.reference
  tests/queries/0_stateless/03447_grouping_sets_analyzer_const_columns.reference
  tests/queries/0_stateless/03447_grouping_sets_analyzer_const_columns.sql
Labels: 25.3, 25.3.6

#917 25.3.6 Backport of #79147: Remove guard pages from fibers and alternative stack for signals in threads
  programs/keeper/Keeper.cpp
  src/Client/BuzzHouse/Generator/FuzzConfig.cpp
  src/Client/ClientBase.cpp
  src/Client/Connection.cpp
  src/Common/AsyncTaskExecutor.cpp
  src/Common/AsyncTaskExecutor.h
  src/Common/FiberStack.cpp
  src/Common/FiberStack.h
  src/Common/ThreadStatus.cpp
  src/Common/memory.cpp
  src/Common/memory.h
  src/Coordination/FourLetterCommand.h
  src/Storages/Distributed/DistributedAsyncInsertBatch.cpp
Labels: 25.3, 25.3.6

#930 Antalya 25.6.5: Forward port of #795 - Parquet Metadata Caching
  programs/server/Server.cpp
  src/Access/Common/AccessType.h
  src/Common/ProfileEvents.cpp
  src/Core/FormatFactorySettings.h
  src/Core/ServerSettings.cpp
  src/Core/SettingsChangesHistory.cpp
  src/Interpreters/InterpreterSystemQuery.cpp
  src/Parsers/ASTSystemQuery.cpp
  src/Parsers/ASTSystemQuery.h
  src/Processors/Formats/IInputFormat.h
  src/Processors/Formats/Impl/ParquetBlockInputFormat.cpp
  src/Processors/Formats/Impl/ParquetBlockInputFormat.h
  src/Processors/Formats/Impl/ParquetFileMetaDataCache.cpp
  src/Processors/Formats/Impl/ParquetFileMetaDataCache.h
  src/Processors/Formats/Impl/ParquetMetadataInputFormat.cpp
  src/Processors/Formats/Impl/ParquetMetadataInputFormat.h
  src/Storages/ObjectStorage/StorageObjectStorageSource.cpp
  tests/queries/0_stateless/01271_show_privileges.reference
  tests/queries/0_stateless/02995_settings_25_2_3.tsv
  tests/queries/0_stateless/03299_parquet_object_storage_metadata_cache.reference
  tests/queries/0_stateless/03299_parquet_object_storage_metadata_cache.sql
Labels: antalya-25.6
